# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniappline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_price',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appart_name', to='uniappline.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tur_obj', to='uniappline.Property'),
        ),
    ]
